# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalendarApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalendarApp
  pod 'CalendarKit', :git => 'https://github.com/bozidarnikolic84/CalendarKit.git'

end
